server:
  port: 18080

spring:
  application:
    name: xht-program
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.213.139:3306/xht_project?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yzd2021

  data:
    redis:
      host: 192.168.213.139
      port: 6379
      database: 0
      connect-timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 8
          min-idle: 0
      password: yzd2021
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 192.168.213.139
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnConfirm
    listener:
      direct:
        acknowledge-mode: manual #手动确认消息被消费

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  config-location: classpath:/mybatis-config.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted #默认deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xht.program

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org:
      springframework:
        jdbc: debug

